### ISSUE TITLE
ignore "CPU Util"

### ISSUE THREAD

**Issue by manajoe** [jrbinks/rancid-arubaoscx#1]
Hi @jrbinks,
at first, thank you so much for your efforts to enable Rancid to grab the config of Aruba OS-Devices, in general it works like charm :-)

I had one "new" little issue, it seems to me, that it only happens since I installed ArubaOS-CX version 10.12.0006 on a switch.
Since then, I get two new lines:
```
"CPU Util (% avg 1 min) : 34"
"CPU Util (% avg 5 min) : 30"
```
in my Rancid config, which of course changes and generates new versions of the config.
With devices with older OS-versions I don't get this information.

I extended your arubaoscx.pm with the following lines after `next if /^CPU Util \(%\)\s+: /;`:
`next if /^CPU Util \(% avg 1 min\)\s+: /;
            next if /^CPU Util \(% avg 5 min\)\s+: /;`

I don't know if this is the best solution, maybe there is a smarter way to achieve this, but it worked ;-)

Thanks, maybe you would like to adapt your code or test for yourself

**Comment by jrbinks** [comment]
Thanks, not running 10.12 anywhere yet.

I think this would be a neater change, added after the current CPU line (it would be possible to merge them, but in my view it gets harder to read):

            next if /^CPU Util \(% avg \d+ min\)\s+: /;

If you can test this and let me know if it is also OK for you, I will commit this change.

**Comment by manajoe** [comment]
Test successful, I substituted my two lines with your one-liner, works! You can commit the change.

Thanks again for your work!

**Comment by jrbinks** [comment]
Now done, many thanks!
