### ISSUE TITLE
environment temperature generates new version

### ISSUE THREAD

**Issue by manajoe** [jrbinks/rancid-arubaoscx#2]
Hello @jrbinks,
I found another little issue in the script, when the temperature is below 10 °C, rancid generates a new version because the amount of whitespace-characters changes:

Switch with temperature above 10 °C (which is usual in our environment):
```
show environment temperature
1/1-Inlet-Air                   management-module    25.38 C    normal
```

Now we have a switch, that is in a quite cold environment:
```
show environment temperature
1/1-Inlet-Air                   management-module    8.38 C     normal
```

With the regex in the script, this changes to these strings, with an additional whitespace for the "cold" one:
```
"normal"
1/1-Inlet-Air                   management-module        normal
"cold"
1/1-Inlet-Air                   management-module         normal
```
If the temperature changes to above 10°C during the next rancid-run, a new version is generated.

Do you have an idea, how to adjust the regex for that?

Thanks and best regards
Manajoe

**Comment by jrbinks** [comment]
Thanks, just seen this. That's a chilly place!  Will have a look.

**Comment by jrbinks** [comment]
Hi again, it was a little more work than I was expecting to sort this, the whitespace got messy.  So I approached it another neater way, and I think this will fix.  It will cause a change for all your devices I'm afraid.

**Comment by manajoe** [comment]
Thanks for your efforts, I‘ll check it after my holidays 😉ManajoeAm 13.08.2023 um 16:53 schrieb J R Binks ***@***.***>:﻿
Hi again, it was a little more work than I was expecting to sort this, the whitespace got messy.  So I approached it another neater way, and I think this will fix.  It will cause a change for all your devices I'm afraid.

**Comment by jrbinks** [comment]
Ha no hurry enjoy your holiday.  I'm running it on my kit now so will see tomorrow!

**Comment by manajoe** [comment]
I'll implemented your fix, now the temperatures "numbers" are no longer included in the config.
Thanks a lot for your efforts!
